# Generated by Django 5.1.7 on 2025-03-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_review_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
    ]
